config/routes.rb
Rails.application.routes.draw do

root 'pages#index'
get '/about', to: 'pages#about'
get '/work', to: 'pages#work'

resources :posts do
  resources :comments
end

resources :sessions

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 3}
  has_many :comments, dependent: :destroy

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_admin
  Admin.find_by(id: session[:id])
end
helper_method :current_admin
# also make this a helper method for use in views

def logged_in?
  !!current_admin
end
helper_method :logged_in?

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
    @comment.name = params[:comment][:name]
    @comment.email = params[:comment][:email]
    @comment.body = params[:comment][:body]
    @comment.save
    redirect_to post_path(@post)
  end

  def show
  end

  # me only
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def index
end

def about
end

def work
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
  if params[:search]
    @posts = Post.search(params[:search]).order('created_at DESC')
  else
    @posts = Post.all.order('created_at DESC')
  end
end

def new
  @post = Post.new
end

def create
   @post = Post.new
   @post.title = params[:post][:title]
   @post.body = params[:post][:body]
   if @post.save
    redirect_to(@post)
  else
    render 'new'
  end
end

def show
  @post = Post.find(params[:id])
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])
  @post.title = params[:post][:title]
  @post.body = params[:post][:body]
  if @post.save
    redirect_to(@post)
  else
    render 'edit'
  end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @admin = Admin.find_by(username: params[:username])
    if @admin && @admin.authenticate(params[:password])
      session[:id] = @admin.id
      redirect_to root_url, notice: "Logged in as #{@admin.username}"
    else
      flash.now.alert = 'Either username or password was incorrect'
      render 'new'
    end
  end

  def destroy
    session[:id] = nil
    redirect_to '/'
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'favicon/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'favicon/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'favicon/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'favicon/apple-touch-icon-76x76.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-96x96.png' %>" sizes="96x96">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/comments/_comment.html.erb
<div class="post-wrapper">
  <p>
    <strong>Name:</strong> <%= comment.name %>
  </p>
  <p><%= comment.body %></p>
  <p><span>Submitted <%= time_ago_in_words(comment.created_at) %> ago.</span></p>
  <% if logged_in? %>
  <p><%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
</div>

app/views/comments/_comments_form.html.erb
<div class="comment">
  <%= form_for([@post, @post.comments.build]) do |f| %>
        <%= f.text_field :name , placeholder: 'Name'%>
        <%= f.text_field :email, placeholder: "Email (won't be displayed online)" %>
        <%= f.text_area :body, placeholder: "Your comment" %>
        <%= f.submit %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Christie Metson</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <%= render 'favicon' %>
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
<meta name="apple-mobile-web-app-capable" content="yes" />
</head>
<body>

  <!-- <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %> -->
  
  <div class="container">
    <div id="largeNav">
      <ul>
        <% if request.path == '/' %>
          <li><%= link_to "Home", root_path, class: "selected" %></li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
        <% end %>

        <% if request.path == '/about' %>
          <li><%= link_to "About", about_path, class: "selected" %></li>
        <% else  %>
        <li><%= link_to "About", about_path %></li>
        <% end %>

        <% if request.path =~ /posts(.*)/ %>
          <li><%= link_to "Journal", posts_path, class: "selected" %></li>
        <% else %>
          <li><%= link_to "Journal", posts_path %></li>
        <% end %>
      </ul>
      <% if logged_in? %>
      <div class="session">
        <p>Hi, <%= current_admin.username %></p>
        <form class="" action="/sessions/<%= current_admin.id %>" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button>Log out</button>
        </form>
      </div>
      <% end %>
    </div>

  </div>

  <div id="smallNav">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <ul id="hamburger">
      <% if request.path == '/' %>
        <li><%= link_to "Home", root_path, class: "selected" %></li>
      <% else %>
        <li><%= link_to "Home", root_path %></li>
      <% end %>

      <% if request.path == '/about' %>
        <li><%= link_to "About", about_path, class: "selected" %></li>
      <% else  %>
      <li><%= link_to "About", about_path %></li>
      <% end %>

      <% if request.path =~ /posts(.*)/ %>
        <li><%= link_to "Journal", posts_path, class: "selected" %></li>
      <% else %>
        <li><%= link_to "Journal", posts_path %></li>
      <% end %>

      <% if logged_in? %>
        <li class="sessionSmall">Hi, <%= current_admin.username %></li>
        <form class="" action="/sessions/<%= current_admin.id %>" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="sessionSmall sessionBtn">Log out</button>
        </form>

        <% end %>
    </ul>
  </div>


  <%= yield %>


</body>
</html>

app/views/pages/about.html.erb
<div class="pages-wrapper">
  <h1>About</h1>
  <div class="container about">
    <p>Hello, I'm Christie, a newly minted web developer living in Melbourne. I'm currently at Realestate.com.au where I was a Business Analyst, before taking a three month arse whipping at General Assembly. I now speak Ruby, Javascript and spend too much time fussing over CSS. From my BA days I'm also experienced in leading agile software delivery projects. I still have index cards in my handbag and love a good scrum.</p>
    <p>If you'd like to know more about struggles of becoming a web developer, check out my thoughts in my journal.</p>
    <p>You can drop me a line at <%= mail_to "christie.arcus@gmail.com" %></p>

    <div class="social-container">
      <a href="https://au.linkedin.com/in/christiemetson"><i class="fa fa-linkedin-square fa-3x" aria-hidden="true"></i></a>
      <a href="https://www.instagram.com/christiemetson/"><i class="fa fa-instagram fa-3x" aria-hidden="true"></i></a>
    </div>
  </div>
</div>
<script src="https://use.fontawesome.com/95e3c94f24.js"></script>

app/views/pages/index.html.erb
<div class="hero-layout">
  <h1 class="animate">Christie Metson</h1>
  <h1>Web Developer</h1>
  <h1><span class="highlight-text">Melbourne, Australia</span></h1>
  <p id="weather"></p>
  </div>

app/views/pages/work.html.erb
<div class="pages-wrapper">
  <h1>Work</h1>
    <div class="container work-squares">

      <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
      	<div class="flipper">
      		<div class="front">
      		</div>
      		<div class="back">
      		</div>
      	</div>
      </div>

      <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
        <div class="flipper">
          <div class="front">
          </div>
          <div class="back">
          </div>
        </div>
      </div>

      <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
        <div class="flipper">
          <div class="front">
          </div>
          <div class="back">
          </div>
        </div>
      </div>

      <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
        <div class="flipper">
          <div class="front">
          </div>
          <div class="back">
          </div>
        </div>
      </div>

    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%= f.text_field :title, placeholder: "Title" %><br>
<%= f.text_area :body, placeholder: "Post body" %><br>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="pages-wrapper container">
  <h1>Edit <%= @post.title %></h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="pages-wrapper container">
  <h1>Journal</h1>

  <% @posts.each do |post| %>
    <div class="post-item">
      <h2><%= link_to post.title, post %></h2>
      <p><%= post.created_at.strftime("%B %d, %Y") %></p>
    </div>
  <% end %>

  <hr></hr>

  <%= form_tag(posts_path, :method => "get", id: "search-form", class: "search") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search" %>
    <%= submit_tag "Go" %>
  <% end %>

  <% if logged_in? %>
  <%= link_to "New", new_post_path %>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="container">
  <% if logged_in? %>
    <h1>New journal entry</h1>
    <%= render 'form' %>
  <% else %>
    <%= link_to "Admin login", new_session_path %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container pages-wrapper">
  <div class="row">
    <div class="post-wrapper">
      <h1><%= @post.title %></h1>
      <p class="time"><%= @post.created_at.strftime("%B %d, %Y") %></p>
      <%= markdown(@post.body) %>

      <% if logged_in? %>
      <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to "Edit", edit_post_path(@post), method: :get%>
      <% end %>
    </div>
  </div>

     <div id="disqus_thread" class="comment-section"></div>
        <script>
            (function() {  // DON'T EDIT BELOW THIS LINE
                var d = document, s = d.createElement('script');
                s.src = '//christiemetson.disqus.com/embed.js';
                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
    </div>
<script id="dsq-count-scr" src="//christiemetson.disqus.com/count.js" async></script>